version: "2"


volumes:
  nginx: {}
  app_db: {}
  app_gems: {}


services:
  app:
    extends:
      file: 'app.yml'
      service: app
    ports:
      - "3000:80"
    env_file:
      - '.env'
    stdin_open: true
    tty: true
  app_db:
    extends:
      file: 'app.yml'
      service: db
